/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeasonChar123seasonChar125TabEpisodeRouteImport } from './routes/season-{$season}.$tab.$episode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonChar123seasonChar125TabEpisodeRoute =
  SeasonChar123seasonChar125TabEpisodeRouteImport.update({
    id: '/season-{$season}/$tab/$episode',
    path: '/season-{$season}/$tab/$episode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/season-{$season}/$tab/$episode': typeof SeasonChar123seasonChar125TabEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/season-{$season}/$tab/$episode': typeof SeasonChar123seasonChar125TabEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/season-{$season}/$tab/$episode': typeof SeasonChar123seasonChar125TabEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/season-{$season}/$tab/$episode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/season-{$season}/$tab/$episode'
  id: '__root__' | '/' | '/season-{$season}/$tab/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeasonChar123seasonChar125TabEpisodeRoute: typeof SeasonChar123seasonChar125TabEpisodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-{$season}/$tab/$episode': {
      id: '/season-{$season}/$tab/$episode'
      path: '/season-{$season}/$tab/$episode'
      fullPath: '/season-{$season}/$tab/$episode'
      preLoaderRoute: typeof SeasonChar123seasonChar125TabEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeasonChar123seasonChar125TabEpisodeRoute:
    SeasonChar123seasonChar125TabEpisodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
